name: advicer
description: flutter bloc clean architecture project

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.2.0


dev_dependencies:
  test: ^1.21.4
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  http_mock_adapter: ^0.3.3

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
